### ISSUE TITLE
Overrides

### ISSUE THREAD

**Issue by dflickinger** [oodesign/merge-duplicate-symbols#24]
Merged symbols lose all Override info.

**Comment by oodesign** [comment]
Hi!
Are you working with Sketch 50? 
We've noticed some of the scripting has changed in this new version. 
A fix is in the works, but it will take some time...

**Comment by dflickinger** [comment]
Dope

**Comment by oodesign** [comment]
Hi @dflickinger !

We just released version 3.0.7, that hopefully will maintain again your instances and nested symbol overrides when using the plugin.

Please, let us know if it did work for you!

Thanks!

**Comment by arianaromo** [comment]
This is still happening! Tried merging a bunch of duplicate symbols and lost all overrides. Had to revert back to the file version right before I started merging.

**Comment by oodesign** [comment]
Hi @arianaromo!

Sorry to hear that.
We're not able to reproduce it with our testing files, though.

May you send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the symbols and its names.

Thanks!

**Comment by grphc-dsgnr** [comment]
I encountered this problem recently too. Lucky for me sketch has a very impressive revert tool.

**Comment by oodesign** [comment]
Hi @grphc-dsgnr !

Looks like many of you are having similar issues. We're still not able to reproduce it with our testing set, though.

May you send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the symbols and its names.

Thanks!

**Comment by oodesign** [comment]
Hi @arianaromo @grphc-dsgnr !

Still having this issue with overrides? Please let us know if you do!

Thanks!
