### ISSUE TITLE
Performance Issue and Crashing

### ISSUE THREAD

**Issue by nickerups** [oodesign/merge-duplicate-symbols#5]
Using Sketch v.46 Plugin 1.1.0

Great idea for a plugin! Sketch needs this so badly.

Unfortunately on my system with a fairly large file, there's some sort of memory leak/performance issue.

I tried to use this on a fairly large file (10 pages, 100+ artboards). Merged 2 symbols and chose to keep the one that was used across 99% of the artboards. Even though only one instance needed to be replaced, the plugin instantly consumes 100% of the CPU usage (according to activity monitor) and the memory slowly creeps up from 3GB to well over 16GB at which point things froze and I reset computer. Tried a couple more times with different symbols and had the same result, but force quit after passing about 14GB usage.

Tried on a smaller file and the plugin still shoots the Sketch CPU usage up to 100%, but it finishes the merge fairly quickly.

**Comment by oodesign** [comment]
Hi! Thanks for the feedback!

We just released an update (v1.1.1) that should fix this performance issues. We're still working on some other fixes, but in the meanwhile... may you give it a try and tell us how did it work for you?

Thank you!

**Comment by RaphyRaph** [comment]
I have v1.1.1 and it still crashes on my first merge attempt :(

**Comment by oodesign** [comment]
May you tell us some more detail about the crash? Are you able to see the first merge screen? Does it crash when you hit "OK" for the very first merge decision? 
Having the original Sketch file would be really helpful. Any chance that you forward us the file, or an adapted version that may be shared?

Thanks!

**Comment by oodesign** [comment]
hi!

We just released version 2.0.0, which adds the "Continue later" option, displays symbol usage data (to ease decision making), and also reduces the performance issues drastically (we changed the way we iterate through layers and pages and works like 3 times faster).

Even though, it will still take some seconds to iterate through all objects if you have lots of pages and layers.

We tested it on a 80 page Sketch file with up to 10 layers per page and gave us performance times lower than 5-6 seconds.

Please, let us know if you're still having issues with it on your files. If you do, having the Sketch files you're trying it on would be really great to test it out.

Thanks!

**Comment by RaphyRaph** [comment]
A lot better! IT mostly works now. Here are some great next steps:
- choose a symbol/multiples symbols and replace all instances of that symbol with another symbol (with the option to keep/override the dimensions)
- offer to merge symbols with the same dimensions (for the case of renamed symbols)
- have a helper that offers to merge symbols when new duplicates get added to the file
- do the same for text styles
THX

**Comment by nickerups** [comment]
Performance is still a bit slow, and CPU usage jumps. But it all works correctly now! Nice work.
